version: '3.8'

services:
  mssql:
    build: ./mssql
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Admin@123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10

  odoo:
    image: odoo:17.0
    container_name: odoo
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=odoo

  odoo_db:
    image: postgres:13
    container_name: odoo_db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_extractor:
    build: ./data_extractor
    container_name: data_extractor
    depends_on:
      - mssql
      - rabbitmq
    environment:
      - MSSQL_HOST=mssql
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=Admin@123
      - RABBITMQ_HOST=rabbitmq

  data_processor:
    build: ./data_processor
    container_name: data_processor
    depends_on:
      - odoo
      - rabbitmq
    environment:
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=odoo
      - ODOO_USER=admin
      - ODOO_PASSWORD=admin
      - RABBITMQ_HOST=rabbitmq

volumes:
  mssql_data:
  odoo_data:
  db_data:
  rabbitmq_data:
